defaultAssertionDataset: superform_assertion
defaultLocation: EU
defaultProject: boodschappen-data
vars:
  GA4_DATASET: analytics_522533558
  LOCAL_TIMEZONE: Europe/Amsterdam
  QUALITY_DATASET: df_quality
  TRANSFORMATIONS_DATASET: df_transformations
  OUTPUTS_DATASET: df_outputs
  REPORTING_DATASET: ga4_reports
  LABEL_GENERIC_BRAND: superformlabs # constant
  LABEL_GENERIC_TOOL: ga4dataform # constant for now...
  LABEL_GENERIC_LICENSE_TYPE: core # core or premium
  LABEL_EXECUTION_OPERATION: daily_workflow # daily_workflow or backfilling
  LABEL_GENERIC_PACKAGE_VERSION: v1-19-0
